# Generated by Django 4.1.4 on 2022-12-15 19:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('main_image', models.ImageField(null=True, upload_to='photos/category_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.PositiveIntegerField(verbose_name='price $')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(900)], verbose_name='discount %')),
                ('final_price', models.PositiveIntegerField(verbose_name='fin_price $')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.product_category', verbose_name='category')),
                ('mnf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.manufacturer', verbose_name='brand')),
            ],
        ),
    ]
