# Generated by Django 4.1.4 on 2022-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_manufacturer_slug_product_slug_product_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='main_image',
            field=models.ImageField(null=True, upload_to='photos/category_photos'),
        ),
    ]
