# Generated by Django 4.1.4 on 2022-12-10 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.PositiveIntegerField(null=True, verbose_name='fin_price $'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.product_category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(900)], verbose_name='discount %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mnf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.manufacturer', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price $'),
        ),
    ]
